# Generated by Django 3.2 on 2021-05-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updadeted_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=75)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
