# Generated by Django 3.2 on 2021-05-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updadeted_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(max_length=22)),
                ('quiz_questions', models.ManyToManyField(to='question.Question')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
