# Generated by Django 3.2 on 2021-05-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210501_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_questions',
        ),
    ]
